services:
  guacd:
    image: guacamole/guacd:1.6.0
    restart: unless-stopped
    networks:
      - guacnet
    volumes:
      - ./drive:/drive
      - ./record:/record

  postgres:
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      - guacnet
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: gtRxA4evf2LarwVqeGqNk57LefMkrf7p
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  guacamole:
    image: guacamole/guacamole:1.6.0
    restart: unless-stopped
    depends_on:
      - guacd
      - postgres
    networks:
      - guacnet
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guacamole_user
      POSTGRESQL_PASSWORD: aE7qVqcrwWb3pT2zJVABskrhNBWHxmtn
      RECORDING_SEARCH_PATH: /record
    volumes:
      - ./record:/record
    expose:
      - "8080"

networks:
  guacnet:
    driver: bridge
